### ISSUE TITLE
Date cannot be cleared

### ISSUE THREAD

**Issue by sibijohn72** [shipshapecode/shipshape.io#122]
I tried 
this.set('dateValue',null); to clear the value in the datepickr but it doesnt work. During debugging i found that this line is executed but it makes no change. There is no error log./
The following is my template code.
{{ember-flatpickr  date=(readonly dateValue)  onChange=(action "onChange")  placeholder="Pick date" }}

**Comment by rwwagner90** [comment]
@sibijohn72 I think you meant to post this issue in ember-flatpickr, this is the Ship Shape website repo. Also, this definitely works, as we're doing it in our example app. Please look there, and if you are still experiencing issues let me know https://github.com/shipshapecode/ember-flatpickr/blob/c2e50facdcb89783adf9355bbc5d248fbe6d7ac8/tests/dummy/app/controllers/docs/components/ember-flatpickr.js#L29
